name = "Mojolicious-Plugin-NamedHelpers"
module_maker="ModuleBuildTiny"
tag_format="v%v"
authority="cpan:TYLDUM"
license="artistic_2"
badges = ['travis','metacpan','codecov']

[FileGatherer]
include_dotfiles = false

